---
- name: Kamailio | Add yum repo.
  become: true
  get_url:
    url: http://download.opensuse.org/repositories/home:/kamailio:/v5.3.x-rpms/CentOS_7/home:kamailio:v5.3.x-rpms.repo
    dest: /etc/yum.repos.d/kamailio.repo

- name: Kamailio | Yum install epel-release.
  become: true
  yum:
    name: epel-release
    state: present

- name: Kamailio | Yum install packages.
  become: true
  yum:
    name: "{{ kamailio_centos7_packages }}"
    state: latest
  notify: Restart kamailio

- name: Kamailio | Configure.
  become: true
  template:
    src: "{{ kamailio_config_template_dir }}/{{ item }}.j2"
    dest: "{{ kamailio_conf_dir }}/{{ item }}"
    backup: true
  with_items: "{{ kamailio_conf_files }}"
  notify: Restart kamailio
  when: kamailio_install_conf

- name: Kamailio | Installing pexpect.
  become: true
  pip:
    name: pexpect

- name: Kamailio | Check if DB exist.
  become: true
  become_user: postgres
  postgresql_db:
    name: kamailio
    state: present
  register: database_exists
      
- name: Kamailio | Create database.
  expect:
    command: /sbin/kamdbctl create
    responses:
      Password: "{{ kamailio_db_root_pass }}"
      (?i)Install: "y"
  run_once: true
  notify: Restart kamailio
  when: kamailio_create_db and database_exists.changed